name: Not My First Workflow
on:
  push:
    branches: 
     - main
  workflow_dispatch:
jobs:
  NotMyFirstJkob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Helow World!"
      - uses: actions/checkout@v4.1.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  
  
